name: Python CI

on:
  push:
    branches: [ main, feat/bootstrap-taskmaster ]
  pull_request:
    branches: [ main, feat/bootstrap-taskmaster ]
  # Adiciona execução agendada (ex: todo Domingo às 3:00 UTC)
  schedule:
    - cron: '0 3 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        OPENAI_API_KEY: dummy
        ASSEMBLYAI_API_KEY: dummy
        R2R_BASE_URL: http://dummy-r2r.local
        R2R_API_KEY: dummy
        SUPABASE_URL: https://dummy.supabase.co
        SUPABASE_SERVICE_KEY: dummy
        SUPABASE_JWT_SECRET: dummysecret123456789012345678901234

    steps:
    - uses: actions/checkout@v4

    # <<< TEMPORARIAMENTE DESABILITADO: CodeQL Init >>>
    # - name: Initialize CodeQL
    #   uses: github/codeql-action/init@v3
    #   with:
    #     languages: python
    #     # config-file: ./.github/codeql/codeql-config.yml # Opcional: para configuração avançada

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # Ajustar se necessário para a versão do projeto
        cache: 'pip' # Habilitar cache de dependências pip

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Assumindo que existe um target 'install-dev' ou similar no Makefile
        make install-dev

    # Teste primeiro
    - name: Test with pytest
      run: |
        make test

    # Lint depois
    - name: Lint with flake8
      run: |
        make lint

    # Auditoria de segurança
    - name: Security Audit Dependencies
      run: |
        # Temporariamente removido pip-audit para simplificar
        # pip install pip-audit
        # pip-audit

    # <<< TEMPORARIAMENTE DESABILITADO: CodeQL Analysis >>>
    # - name: Perform CodeQL Analysis
    #   uses: github/codeql-action/analyze@v3
    #   with:
    #     category: "/language:python"
        
    # REMOVIDO: Passo de Upload do Artefato não aplicável 
    # - name: Upload artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: application-artifact-${{ github.sha }}
    #     path: dist/ 